version: '3.8'

services:
  client:
    build:
      target: production
    environment:
      NODE_ENV: production
      # VITE_GRAPHQL_URI: http://localhost:3000
      # VITE_PORT: 8080
    expose:
      - '8080'
    ports:
      - "8080:8080"
    container_name: client
    command: npm run preview

  api:
    build:
      target: production
    environment:
      NODE_ENV: production
      DATABASE_URL: 
      PORT: 3000
    container_name: api
    expose:
      - '3000'
    ports:
      - "3000:3000"
    command: npm run start